### ISSUE TITLE
Allow thumbnailers to work on FreeBSD

### ISSUE THREAD

**Issue by probonopd** [linuxmint/xapp-thumbnailers#1]
Thanks for creating these thumbnailers, which are _very_ useful.

Currently the shebang `#!/usr/bin/python3` is used.

By changing it to `#!/usr/bin/env python3` the thumbnailers can also work on FreeBSD which is using `/usr/local/bin/python3`.

**Comment by clefebvre** [comment]
Please path locally @probonopd, we can't use env here, it leads to all sorts of problems.

**Comment by probonopd** [comment]
OK, doing that. Thanks @clefebvre
