### ISSUE TITLE
Please add support for GIMP 2.10.x (.xcf) files

### ISSUE THREAD

**Issue by gimplyworxs** [linuxmint/xapp-thumbnailers#13]
It would be nice to have thumbnails for .xcf files of GIMP 2.10.x and possibly 3.x

**Comment by mtwebster** [comment]
https://github.com/linuxmint/xapp-thumbnailers/commit/034836faa6f1b56f2263c8a062e4581ab540da73

**Comment by gimplyworxs** [comment]
Is it possible to get this to work on Mint 20.x?

**Comment by mtwebster** [comment]
You can download [this file](https://github.com/linuxmint/xapp-thumbnailers/raw/master/files/usr/share/thumbnailers/xapp-gimp-thumbnailer.thumbnailer) and put it in `/usr/share/thumbnailers`

Then download [this script](https://github.com/linuxmint/xapp-thumbnailers/raw/master/files/usr/bin/xapp-gimp-thumbnailer) and put it in `/usr/bin`, then ensure it's executable by running `chmod +x /usr/bin/xapp-gimp-thumbnailer`.

Exit all nemo windows then restart it. Unless the gimp version in 20.x doesn't support all of the commands being used, it should work.

It's also fairly slow as well - don't expect blazing speed, there's not much I can do about that.

**Comment by gimplyworxs** [comment]
Looks like Mint 20.x is not suitable, which is a pity.
It seems to miss the XappThumbnailers module.
Got it and placed it where all the other python modules are, but still no luck.

I guess I'll have to update the system soon.
Thanks anyway.
